# Generated by Django 5.1 on 2024-08-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resrestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish', models.CharField(max_length=20)),
                ('cost', models.IntegerField(max_length=100)),
            ],
        ),
    ]
