# Generated by Django 5.1 on 2024-08-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resrestaurant',
            new_name='item',
        ),
    ]
